stages:
- pubpages_deploy
variables:
  CI_JOB_TOKEN: 10a5fd19948851047e268e051b9592
  #DOCKER_AUTH_CONFIG: '{ "auths": {"registry.gitlab.com": {"auth": Y2xpZW50LXBpcGVsaW5lLWltYWdlczpLSDVYQW5pOW9pN1NKdlpCYmlydg=="} } }'

rootfolder_deploy:
  image: alpine:3.16.0
  stage: pubpages_deploy
  script:
  - apk update
  - apk add curl
  - echo 'initiate external repo  pipeline'
  #- curl -X POST -F token=c233493f7301919c291ad9543afd4a -F ref=master -F "variables[NEWPUBPAGES]=dev" https://gitlab.com/api/v4/projects/26394747/trigger/pipeline
  - curl -X POST -F token=ca0292c16c292267238f50f30960b2 -F ref=master  -F "variables[NEWPUBPAGES]=dev" https://gitlab.scriptbees.com/api/v4/projects/815/trigger/pipeline
  


  tags:
  - groupms  
